name: study_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.4
  permission_handler: ^12.0.0+1
  intl: ^0.20.2
  google_mobile_ads: ^4.0.0
  qr_flutter: ^4.0.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  firebase_storage: ^12.4.5
  table_calendar: ^3.0.9 
  flutter_rating_bar: ^4.0.0
  flip_card: ^0.6.0
  flutter_launcher_icons: ^0.14.3
  http: ^1.4.0
  timeago: ^3.7.1
  provider: ^6.1.5
  multi_select_flutter: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/5900198.png"