name: study_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter  # Thư viện Flutter chính, bắt buộc
  cupertino_icons: ^1.0.8  # Biểu tượng theo phong cách iOS (Cupertino)
  image_picker: ^1.0.4  # Dùng để chọn ảnh từ gallery hoặc chụp ảnh
  permission_handler: ^12.0.0+1  # Xử lý quyền truy cập (camera, bộ nhớ, v.v.)
  intl: ^0.20.2  # Hỗ trợ định dạng ngày, giờ, tiền tệ, đa ngôn ngữ
  google_mobile_ads: ^4.0.0  # Tích hợp quảng cáo AdMob
  qr_flutter: ^4.0.0  # Tạo và hiển thị mã QR
  firebase_core: ^3.13.0  # Bắt buộc để khởi tạo Firebase
  firebase_auth: ^5.5.3  # Xác thực người dùng bằng Firebase
  cloud_firestore: ^5.6.7  # Dùng cơ sở dữ liệu thời gian thực Firestore
  firebase_storage: ^12.4.5  # Lưu trữ tệp trên Firebase (ảnh, video)
  table_calendar: ^3.0.9  # Widget lịch, hỗ trợ chọn ngày/sự kiện
  flutter_rating_bar: ^4.0.0  # Tạo thanh đánh giá bằng sao
  flip_card: ^0.6.0  # Tạo hiệu ứng lật thẻ (card flip)
  flutter_launcher_icons: ^0.14.3  # Tự động tạo icon ứng dụng
  http: ^1.4.0  # Gửi và nhận dữ liệu từ API qua HTTP
  timeago: ^3.7.1  # Hiển thị thời gian như "3 phút trước"
  provider: ^6.1.5  # Quản lý trạng thái (state management)
  multi_select_flutter: ^4.1.3  # Cho phép chọn nhiều mục (multi select)

dev_dependencies:
  flutter_test:
    sdk: flutter  # Thư viện để viết unit test và widget test
  flutter_lints: ^5.0.0  # Bộ quy tắc kiểm tra code chuẩn trong Flutter


flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/5900198.png"