// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpxRG8sN0-1onp4kmHO2oEzhPr9BmUB24',
    appId: '1:1038745924617:web:47460c52ecc578f046f4d8',
    messagingSenderId: '1038745924617',
    projectId: 'bookshop-2b06c',
    authDomain: 'bookshop-2b06c.firebaseapp.com',
    storageBucket: 'bookshop-2b06c.firebasestorage.app',
    measurementId: 'G-Z1W1ZK4Q22',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYbn-C0qUbSxo7IpEZgjbad6AUo5tpYQc',
    appId: '1:1038745924617:android:a1a38090a007fc8746f4d8',
    messagingSenderId: '1038745924617',
    projectId: 'bookshop-2b06c',
    storageBucket: 'bookshop-2b06c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzZ7jNBbDv-XnJunuuOZQW1fJQcqNte20',
    appId: '1:1038745924617:ios:4d28d01cab5532a846f4d8',
    messagingSenderId: '1038745924617',
    projectId: 'bookshop-2b06c',
    storageBucket: 'bookshop-2b06c.firebasestorage.app',
    iosBundleId: 'com.example.studyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzZ7jNBbDv-XnJunuuOZQW1fJQcqNte20',
    appId: '1:1038745924617:ios:4d28d01cab5532a846f4d8',
    messagingSenderId: '1038745924617',
    projectId: 'bookshop-2b06c',
    storageBucket: 'bookshop-2b06c.firebasestorage.app',
    iosBundleId: 'com.example.studyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpxRG8sN0-1onp4kmHO2oEzhPr9BmUB24',
    appId: '1:1038745924617:web:5598bc2531d4885b46f4d8',
    messagingSenderId: '1038745924617',
    projectId: 'bookshop-2b06c',
    authDomain: 'bookshop-2b06c.firebaseapp.com',
    storageBucket: 'bookshop-2b06c.firebasestorage.app',
    measurementId: 'G-EPN5GVGVQM',
  );
}
